---
abstract: 'Log to FirePHP from within HTTP::Engine'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Engine-FirePHP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  FirePHP::Dispatcher: 0
  HTTP::Engine::Response: 0
  HTTP::Headers::Fast: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=HTTP-Engine-FirePHP
  homepage: http://search.cpan.org/dist/HTTP-Engine-FirePHP/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/hanekomu/http-engine-firephp/tree/master
version: 0.01
